version: 0.0
os: linux
files:
  - source: /
    destination: /webapps/app
  - source: CodeDeploy/uwsgi.service
    destination: /etc/systemd/system/
    file_exist_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: CodeDeploy/configure_software.sh
      timeout: 500
      runas: root
    - location: CodeDeploy/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: CodeDeploy/stop_server.sh
      timeout: 300
      runas: root