version: 0.2

env:
  variables:
    DATABASE_HOST: "localhost"
    DATABASE_USER: "web_user"
    DATABASE_PASSWORD: "1keytone"
    DATABASE_DB_NAME: "routes"

phases:
  install:
    commands:
      - echo Install started on `date`
      - yum -y install python3
      - pip3 install -r FlaskApp/requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - cd FlaskApp
      - python3 -m pylint *.py
      # - nosetests --cover-html --with-coverage --cover-erase --cover-package=.
      - echo "Running unit tests with unittest..."
      - python3 -m unittest discover -s . -p "test_*.py" -v
      - coverage run -m unittest discover -s . -p "test_*.py" # To generate coverage data
      - coverage html -d coverage_report
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - 'FlaskApp/cover/*'